title: My Site
markdown: kramdown
kramdown: 
  math_engine: katex

# permalink: pretty
paginate: 3
toc:
  sublist_class: sub-list
paginate_path: "/page:num"
collections:
  posts_en:
    output: true
    permalink: /en/:categories/:title
permalink: /:categories/:title
plugins:
  - jekyll-toc
  - jekyll-paginate
# collections: 
#   my_collection:
#     output: true
#     permalink: /:categories/:output_ext